### ISSUE TITLE
v2.0.2 didn’t get published 

### ISSUE THREAD

**Issue by mxschmitt** [conda-forge/greenlet-feedstock#32]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

v2.0.2 is [not on conda](https://anaconda.org/anaconda/greenlet) but on [PyPi](https://pypi.org/project/greenlet/).

https://github.com/conda-forge/greenlet-feedstock/commit/8deb30e52ac98f97f3eef98e9b28411576b1f44e pipeline/status check seems to have failed

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by mxschmitt** [comment]
Looks like a temporary issue, a restart of the Azure Pipeline might help here. @xhochy do you mind restarting it? Thanks!

**Comment by xhochy** [comment]
This doesn't look like a pure CI issue. Except a single build everything passed and still there is no file showing up. 🤔

**Comment by xhochy** [comment]
The version is now visible.

**Comment by mxschmitt** [comment]
Thanks!
